# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'RP_MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(650, 600)
        MainWindow.setMinimumSize(QSize(800, 600))
        self.action_openreport = QAction(MainWindow)
        self.action_openreport.setObjectName(u"action_openreport")
        self.action_opendatafile = QAction(MainWindow)
        self.action_opendatafile.setObjectName(u"action_opendatafile")
        self.action_loadselect = QAction(MainWindow)
        self.action_loadselect.setObjectName(u"action_loadselect")
        self.action_set_execl = QAction(MainWindow)
        self.action_set_execl.setObjectName(u"action_set_execl")
        self.action_set_txt = QAction(MainWindow)
        self.action_set_txt.setObjectName(u"action_set_txt")
        self.action_set_select = QAction(MainWindow)
        self.action_set_select.setObjectName(u"action_set_select")
        self.action_sets_import = QAction(MainWindow)
        self.action_sets_import.setObjectName(u"action_sets_import")
        self.action_sets_export = QAction(MainWindow)
        self.action_sets_export.setObjectName(u"action_sets_export")
        self.action_savereport = QAction(MainWindow)
        self.action_savereport.setObjectName(u"action_savereport")
        self.action_quitapp = QAction(MainWindow)
        self.action_quitapp.setObjectName(u"action_quitapp")
        self.action_saveselects = QAction(MainWindow)
        self.action_saveselects.setObjectName(u"action_saveselects")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 650, 22))
        self.menu_rp = QMenu(self.menubar)
        self.menu_rp.setObjectName(u"menu_rp")
        self.menu_data = QMenu(self.menubar)
        self.menu_data.setObjectName(u"menu_data")
        self.menu_setting = QMenu(self.menubar)
        self.menu_setting.setObjectName(u"menu_setting")
        self.menu_save = QMenu(self.menubar)
        self.menu_save.setObjectName(u"menu_save")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.menubar.addAction(self.menu_rp.menuAction())
        self.menubar.addAction(self.menu_data.menuAction())
        self.menubar.addAction(self.menu_setting.menuAction())
        self.menu_rp.addAction(self.action_openreport)
        self.menu_rp.addAction(self.action_savereport)
        self.menu_rp.addSeparator()
        self.menu_rp.addAction(self.action_quitapp)
        self.menu_data.addAction(self.action_opendatafile)
        self.menu_data.addAction(self.action_loadselect)
        self.menu_data.addAction(self.action_saveselects)
        self.menu_setting.addAction(self.action_set_execl)
        self.menu_setting.addAction(self.action_set_txt)
        self.menu_setting.addAction(self.action_set_select)
        self.menu_setting.addSeparator()
        self.menu_setting.addAction(self.action_sets_import)
        self.menu_setting.addAction(self.action_sets_export)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action_openreport.setText(QCoreApplication.translate("MainWindow", u"打开报告", None))
#if QT_CONFIG(shortcut)
        self.action_openreport.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.action_opendatafile.setText(QCoreApplication.translate("MainWindow", u"打开数据文件", None))
#if QT_CONFIG(shortcut)
        self.action_opendatafile.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.action_loadselect.setText(QCoreApplication.translate("MainWindow", u"加载选择", None))
#if QT_CONFIG(tooltip)
        self.action_loadselect.setToolTip(QCoreApplication.translate("MainWindow", u"加载之前保存的选择", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_loadselect.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.action_set_execl.setText(QCoreApplication.translate("MainWindow", u"报告设置", None))
#if QT_CONFIG(tooltip)
        self.action_set_execl.setToolTip(QCoreApplication.translate("MainWindow", u"execl相关的设置", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_set_execl.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+E", None))
#endif // QT_CONFIG(shortcut)
        self.action_set_txt.setText(QCoreApplication.translate("MainWindow", u"数据源设置", None))
#if QT_CONFIG(tooltip)
        self.action_set_txt.setToolTip(QCoreApplication.translate("MainWindow", u"txt相关的设置", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_set_txt.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+T", None))
#endif // QT_CONFIG(shortcut)
        self.action_set_select.setText(QCoreApplication.translate("MainWindow", u"配置select", None))
#if QT_CONFIG(tooltip)
        self.action_set_select.setToolTip(QCoreApplication.translate("MainWindow", u"select相关的设置", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_set_select.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_sets_import.setText(QCoreApplication.translate("MainWindow", u"导入配置", None))
#if QT_CONFIG(shortcut)
        self.action_sets_import.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+I", None))
#endif // QT_CONFIG(shortcut)
        self.action_sets_export.setText(QCoreApplication.translate("MainWindow", u"导出配置", None))
#if QT_CONFIG(shortcut)
        self.action_sets_export.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+O", None))
#endif // QT_CONFIG(shortcut)
        self.action_savereport.setText(QCoreApplication.translate("MainWindow", u"保存报告", None))
#if QT_CONFIG(shortcut)
        self.action_savereport.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_quitapp.setText(QCoreApplication.translate("MainWindow", u"退出", None))
        self.action_saveselects.setText(QCoreApplication.translate("MainWindow", u"保存选择", None))
#if QT_CONFIG(shortcut)
        self.action_saveselects.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+B", None))
#endif // QT_CONFIG(shortcut)
        self.menu_rp.setTitle(QCoreApplication.translate("MainWindow", u"报告", None))
        self.menu_data.setTitle(QCoreApplication.translate("MainWindow", u"数据", None))
        self.menu_setting.setTitle(QCoreApplication.translate("MainWindow", u"设置", None))
        self.menu_save.setTitle(QCoreApplication.translate("MainWindow", u"保存", None))
    # retranslateUi

