# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'RP_MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(650, 600)
        MainWindow.setMinimumSize(QSize(600, 400))
        self.action_openfolder = QAction(MainWindow)
        self.action_openfolder.setObjectName(u"action_openfolder")
        icon = QIcon(QIcon.fromTheme(u"applications-office"))
        self.action_openfolder.setIcon(icon)
        self.action_openreport = QAction(MainWindow)
        self.action_openreport.setObjectName(u"action_openreport")
        self.action_opendatafile = QAction(MainWindow)
        self.action_opendatafile.setObjectName(u"action_opendatafile")
        self.action_loadselect = QAction(MainWindow)
        self.action_loadselect.setObjectName(u"action_loadselect")
        self.action_set_execl = QAction(MainWindow)
        self.action_set_execl.setObjectName(u"action_set_execl")
        self.action_set_txt = QAction(MainWindow)
        self.action_set_txt.setObjectName(u"action_set_txt")
        self.action_set_select = QAction(MainWindow)
        self.action_set_select.setObjectName(u"action_set_select")
        self.action_sets_import = QAction(MainWindow)
        self.action_sets_import.setObjectName(u"action_sets_import")
        self.action_sets_export = QAction(MainWindow)
        self.action_sets_export.setObjectName(u"action_sets_export")
        self.action_saveselect = QAction(MainWindow)
        self.action_saveselect.setObjectName(u"action_saveselect")
        self.action_quitapp = QAction(MainWindow)
        self.action_quitapp.setObjectName(u"action_quitapp")
        self.action_quitapp.setEnabled(True)
        self.action_quitapp.setMenuRole(QAction.QuitRole)
        self.action_savereport = QAction(MainWindow)
        self.action_savereport.setObjectName(u"action_savereport")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 650, 21))
        self.menu_rp = QMenu(self.menubar)
        self.menu_rp.setObjectName(u"menu_rp")
        self.menu_data = QMenu(self.menubar)
        self.menu_data.setObjectName(u"menu_data")
        self.menu_setting = QMenu(self.menubar)
        self.menu_setting.setObjectName(u"menu_setting")
        self.menu_save = QMenu(self.menubar)
        self.menu_save.setObjectName(u"menu_save")
        self.menu_quit = QMenu(self.menubar)
        self.menu_quit.setObjectName(u"menu_quit")
        self.menu_quit.setTearOffEnabled(False)
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.menubar.addAction(self.menu_rp.menuAction())
        self.menubar.addAction(self.menu_data.menuAction())
        self.menubar.addAction(self.menu_setting.menuAction())
        self.menubar.addAction(self.menu_save.menuAction())
        self.menubar.addAction(self.menu_quit.menuAction())
        self.menu_rp.addAction(self.action_openfolder)
        self.menu_rp.addAction(self.action_openreport)
        self.menu_data.addAction(self.action_opendatafile)
        self.menu_data.addAction(self.action_loadselect)
        self.menu_data.addAction(self.action_saveselect)
        self.menu_setting.addAction(self.action_set_execl)
        self.menu_setting.addAction(self.action_set_txt)
        self.menu_setting.addAction(self.action_set_select)
        self.menu_setting.addSeparator()
        self.menu_setting.addAction(self.action_sets_import)
        self.menu_setting.addAction(self.action_sets_export)
        self.menu_save.addAction(self.action_savereport)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action_openfolder.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u57fa\u6587\u4ef6\u5939", None))
#if QT_CONFIG(tooltip)
        self.action_openfolder.setToolTip(QCoreApplication.translate("MainWindow", u"\u8bf7\u9009\u62e9\u62a5\u544a\u548c\u6570\u636e\u6240\u5728\u7684\u6587\u4ef6\u5939", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_openfolder.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.action_openreport.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u62a5\u544a", None))
#if QT_CONFIG(shortcut)
        self.action_openreport.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.action_opendatafile.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6570\u636e\u6587\u4ef6", None))
#if QT_CONFIG(shortcut)
        self.action_opendatafile.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.action_loadselect.setText(QCoreApplication.translate("MainWindow", u"\u52a0\u8f7d\u9009\u62e9", None))
#if QT_CONFIG(tooltip)
        self.action_loadselect.setToolTip(QCoreApplication.translate("MainWindow", u"\u52a0\u8f7d\u4e4b\u524d\u4fdd\u5b58\u7684\u9009\u62e9", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_loadselect.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.action_set_execl.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6eexecl", None))
#if QT_CONFIG(tooltip)
        self.action_set_execl.setToolTip(QCoreApplication.translate("MainWindow", u"execl\u76f8\u5173\u7684\u8bbe\u7f6e", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_set_execl.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+E", None))
#endif // QT_CONFIG(shortcut)
        self.action_set_txt.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6etxt", None))
#if QT_CONFIG(tooltip)
        self.action_set_txt.setToolTip(QCoreApplication.translate("MainWindow", u"txt\u76f8\u5173\u7684\u8bbe\u7f6e", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_set_txt.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+T", None))
#endif // QT_CONFIG(shortcut)
        self.action_set_select.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6eselect", None))
#if QT_CONFIG(tooltip)
        self.action_set_select.setToolTip(QCoreApplication.translate("MainWindow", u"select\u76f8\u5173\u7684\u8bbe\u7f6e", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_set_select.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_sets_import.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165\u914d\u7f6e", None))
#if QT_CONFIG(shortcut)
        self.action_sets_import.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+I", None))
#endif // QT_CONFIG(shortcut)
        self.action_sets_export.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa\u914d\u7f6e", None))
#if QT_CONFIG(shortcut)
        self.action_sets_export.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+O", None))
#endif // QT_CONFIG(shortcut)
        self.action_saveselect.setText(QCoreApplication.translate("MainWindow", u"\u53e6\u5b58\u9009\u62e9", None))
#if QT_CONFIG(tooltip)
        self.action_saveselect.setToolTip(QCoreApplication.translate("MainWindow", u"\u53e6\u5b58\u9009\u62e9\u4e3a\u5176\u4ed6\u540d\u79f0", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_saveselect.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_quitapp.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
#if QT_CONFIG(tooltip)
        self.action_quitapp.setToolTip(QCoreApplication.translate("MainWindow", u"\u9000\u51fa\u7a0b\u5e8f", None))
#endif // QT_CONFIG(tooltip)
        self.action_savereport.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u62a5\u544a", None))
        self.menu_rp.setTitle(QCoreApplication.translate("MainWindow", u"\u62a5\u544a", None))
        self.menu_data.setTitle(QCoreApplication.translate("MainWindow", u"\u6570\u636e", None))
        self.menu_setting.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.menu_save.setTitle(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
        self.menu_quit.setTitle(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
    # retranslateUi

